USE master

if NOT EXISTS(SELECT * FROM sys.databases WHERE NAME='DB_EVENTOS' )
CREATE DATABASE DB_EVENTOS
ON
(
NAME = DB_EVENTOS_DAT,
FILENAME = 'C:\Users\sinqia\Documents\Sinqia_AspNet\data',
SIZE= 5000KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1000KB
)
LOG ON
(
NAME = DB_EVENTOS_LOG,
FILENAME = 'C:\Users\sinqia\Documents\Sinqia_AspNet\data',
SIZE= 2000KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1000KB
)
GO